### ISSUE TITLE
Add "forward to a friend" CTA

### ISSUE THREAD

**Issue by alisondavis17** [resin-io/resin-emails#7]
We should add a link / CTA for newsletter subscribers to forward the newsletter to their friends. We should then measure the forward rate.

**Comment by lurch** [comment]
Would people actually use this though, rather than just clicking on the "Forward" button in their email client?
(TBH I've no idea if other email newsletters already include something similar though - maybe it's a common usage pattern that I'm not aware of)

**Comment by alisondavis17** [comment]
It is a common pattern in newsletters, for a couple reasons - one, it's an explicit call to action that a subscriber may not think to do without being prompted. Two, it allows us to easily track how many people are forwarding to their friends, which is kind of a proxy for "recommending" resin, or tracking word-of-mouth recommendations. 

Seems worth testing for a couple newsletters and if nobody uses it, we can abandon.

**Comment by lurch** [comment]
...and I guess it also gives you the email address of the friend they forwarded it onto ;-)

**Comment by imrehg** [comment]
Andrew: many newsletters don't work when you just forward it because eg.
the person you forwarded to can unsubscribe you from the newsletter (those
are personalized links to each receiver). Thus newsletter providers have
workarounds to have "neutral" forwardable versions.

And to the best of my knowledge none of them gives you the address of the
person it is forwarded to, just possibly analytics on who clicked that link
in the mail (like other link clicks that are recorded).

**Comment by lurch** [comment]
Thanks for the info @imrehg :+1:

**Comment by imrehg** [comment]
@alisondavis17 @craig-mulligan this is done by adding the `*|FORWARD|*` merge tag to the email, for example as:
```
<a href="*|FORWARD|*">Forward this email to a friend</a>
```
So technically it's pretty easy, but where would it be good to put in the email, and what exact text to use? Maybe after the socal callout? [Here's the last newsletter for reference](http://us3.campaign-archive1.com/?u=87871f17defba2d203db77a92&id=b4e575ed02).

Here's [the article on the Mailchimp KB](http://kb.mailchimp.com/campaigns/design/add-the-forward-to-a-friend-link) regarding forward to a friend.

**Comment by alisondavis17** [comment]
@imrehg I usually look for it near the header or footer. 

Here's some examples of newsletter sharing strategies I've seen - including "forward to a friend" style CTAs as well as social media sharing links: 

<img width="679" alt="screen shot 2017-02-20 at 7 19 15 pm" src="https://cloud.githubusercontent.com/assets/20308284/23149565/9b7040dc-f7a1-11e6-9b91-df65c33bd8d3.png">

<img width="609" alt="screen shot 2017-02-20 at 7 22 01 pm" src="https://cloud.githubusercontent.com/assets/20308284/23149678/8e9bc3da-f7a2-11e6-82d7-ab661d481ec2.png">

<img width="766" alt="screen shot 2017-02-20 at 7 25 58 pm" src="https://cloud.githubusercontent.com/assets/20308284/23149679/8e9c2a0a-f7a2-11e6-80fd-c27261a76243.png">

Some of the "share with a friend" links open up a new window, like the one below. 

<img width="496" alt="screen shot 2017-02-20 at 7 26 29 pm" src="https://cloud.githubusercontent.com/assets/20308284/23149680/8e9c5e30-f7a2-11e6-81df-64aa06ffa288.png">

**Comment by lurch** [comment]
That's weird, does it not pre-fill in the "Your Email" box based on the unique ID in the "share with a friend" link?
(And on a side-note, it seems weird to have a "Sign Up!" link in a newsletter - presumably you must _already_ be signed up to actually be getting the newsletter?) I'll go crawl back under my rock now ;-)

**Comment by imrehg** [comment]
@lurch :) I've checked out on another mailing list that has `forward to a friend`, it does not look like it's customized to your email, rather it's a single custom link created the specific newsletter edition, without any user identification. So that's why they don't prefill, I'm guessing. 

The "Sign-up" makes sense for the case when people received the email from forward. I've seen this pattern in other newsletters too.

**Comment by imrehg** [comment]
Added a work-in-progress simple version as PR. Looks like this:

![forward_friend](https://cloud.githubusercontent.com/assets/38863/23224353/ebc65f32-f925-11e6-8fb6-6980187f1968.png)

**Comment by lurch** [comment]
...and I guess you need to update the "You are receiving this newsletter because..." snippet if you're getting the email because a friend forwarded it to you ;-)

**Comment by imrehg** [comment]
@lurch tried it out, and not necessary. The forward links sends your personal message + a link to the web archive link to the designated "friend", so it's clear that you are checking a past message of the newsletter on the web at your own convenience.

**Comment by lurch** [comment]
Ahhh, I didn't realise the "forward to a friend" only forwarded a web link, and not the (contents of the) newsletter itself :)

**Comment by imrehg** [comment]
Yup, that's why I tried it out, as I didn't quite know either ;)
